### ISSUE TITLE
[TC Fase 2] Etapa 1 - A lista de pedidos deverá retorná-los com suas descrições, ordenados com a seguinte regra

### ISSUE THREAD

**Issue by RenanSX** [RenanSX/tech-challenge#83]
1 . Pronto > Em Preparação > Recebido;
2 . Pedidos mais antigos primeiro e mais novos depois
3. Pedidos com status Finalizado não devem aparecer na lista

**Comment by victorhiga2018** [comment]
Resolvido na PR:

https://github.com/RenanSX/tech-challenge/pull/98
